### ISSUE TITLE
too many -Wconvert warnings

### ISSUE THREAD

**Issue by puzrin** [ETLCPP/etl#157]
`-Wconvert` is useful to search suspicious places. But since ETL is header-based, it's warnings can not be suppressed. Could you fix or, at least, reduce number of such warnings for ETL?

**Comment by kiciek** [comment]
It can be suppressed in newer versions of GCC (in 9+ it can be. no idea whet in happened) by marking includes as SYSTEM. In cmake it is made wist `include_directories(SYSTEM etl/include)`, and without cmake all you need to do is use `-isystem ` instead of `-I` 
Older versions of GCC don't allow templates in system headers. Currently, I suppress a list of warnings in each file with etl include:
```
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Weffc++"
#pragma GCC diagnostic ignored "-Wold-style-cast"
#pragma GCC diagnostic ignored "-Wnon-virtual-dtor" // not sure about that
#pragma GCC diagnostic ignored "-Wsuggest-override"
#pragma GCC diagnostic ignored "-Wmultiple-inheritance"
#pragma GCC diagnostic ignored "-Wctor-dtor-privacy"
#pragma GCC diagnostic ignored "-Wcast-qual"
#pragma GCC diagnostic ignored "-Wconditionally-supported"

#include "etl/fsm.h"

#pragma GCC diagnostic pop
```
