### ISSUE TITLE
Ambiguous string, vector, etc. realizations for byte coping purpose

### ISSUE THREAD

**Issue by mrdimfox** [ETLCPP/etl#30]
If you have some object of type string<N> and you try to make memcpy of it, you find out that method data() of copied obj returns a wrong pointer to the buffer. It happens because of the string<N> class stores the buffer's pointer separately in the base class but while copying the real address of the buffer is changed. It can be critical for some embedded purposes.

**Comment by jwellbelove** [comment]
Using memcpy on C++ objects is usually a very bad idea. It can be easily broken by changes to the class or its bases, as you have found.I've had to spend ages in the past where a developer memcpy'd a class in a number of places, which caused issues when a new member was added to it. The bug was subtle and time consuming to track down. Don't do it.On 05 June 2017 at 16:17 MrDimLis <notifications@github.com> wrote:If you have some object of type string and you try to make memcpy of it, you find out that method data() of copied obj returns an ambiguous pointer to the buffer. It happens because of the string class stores the buffer's pointer separately in the base class but while copying the real address of the buffer is changed. It can be critical for some embedded purposes.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by mrdimfox** [comment]
> Using memcpy on C++ objects is usually a very bad idea

Yes, I fully agree with you. But we have deal with implementations of std containers for embedded proposes so it will be very useful to resolve this issue. 
For example, if I use queues in the FreeRTOS OS, I can't avoid memcpy, cause FreeRTOS use it for all stuff placed in queues.

**Comment by jwellbelove** [comment]
Any view on my suggestion?The 'fixup' option would be relatively simple to implement for strings, vector and possibly deque.A quick test shows it to be a viable, low-level option.On 05 June 2017 at 16:17 MrDimLis <notifications@github.com> wrote:If you have some object of type string and you try to make memcpy of it, you find out that method data() of copied obj returns an ambiguous pointer to the buffer. It happens because of the string class stores the buffer's pointer separately in the base class but while copying the real address of the buffer is changed. It can be critical for some embedded purposes.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by mrdimfox** [comment]
> Any view on my suggestion?

@jwellbelove, I've already answered you above, that I agree with you. But there are some cases, for example when we use some C libs, we can't avoid a memcpy cause we can't change the implementation.

**Comment by jwellbelove** [comment]
I meant the suggestion that I add a fixup() function to the top level of the container classes to repair the internal pointer after a memcpy to a raw buffer, and a reinterpret cast back from a raw pointer to the original container reference.On 15 June 2017 at 12:10 MrDimLis <notifications@github.com> wrote:Any view on my suggestion?@jwellbelove, I've already answered you above, that I agree with you. But there are some cases, for example when we use some C libs, we can't avoid a memcpy cause we can't change the implementation.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by mrdimfox** [comment]
Oh, okay. I think it would be great.
