### ISSUE TITLE
problem with alignment on platforms that don't support int8_t

### ISSUE THREAD

**Issue by RallyTronics** [ETLCPP/etl#31]
working on a TI platform that does not support an 8-bit data type I get errors such as:

"alignment.h", line 99: error: 
          identifier "int8_t" is undefined
      typedef typename __private_alignment__::type_with_alignment_helper<ALIGNMENT, int8_t, int16_t, int32_t, int64_t, float, double, void*>::type type;

this is the offending template:

  ```
template <const size_t ALIGNMENT>
  class type_with_alignment
  {
  public:

    typedef typename __private_alignment__::type_with_alignment_helper<ALIGNMENT, int8_t, int16_t, int32_t, int64_t, float, double, void*>::type type;
  };

```

for now I have defined uint8_t=uint16_t

there should probably be a check based on your ETL_8BIT_SUPPORT macro

**Comment by jwellbelove** [comment]
Thanks, I'll either add an #ifdef to the code or look to see if changing the uint8_t to uint_least8_t would work.On 06 June 2017 at 21:34 John Lagerquist <notifications@github.com> wrote:working on a TI platform that does not support an 8-bit data type I get errors such as:"alignment.h", line 99: error: identifier "int8_t" is undefined typedef typename private_alignment::type_with_alignment_helper<ALIGNMENT, int8_t, int16_t, int32_t, int64_t, float, double, void*>::type type;this is the offending template:template <const size_t ALIGNMENT>
class type_with_alignment
{
public:

  typedef typename __private_alignment__::type_with_alignment_helper<ALIGNMENT, int8_t, int16_t, int32_t, int64_t, float, double, void*>::type type;
};

for now I have defined uint8_t=uint16_tthere should probably be a check based on your ETL_8BIT_SUPPORT macro—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by jwellbelove** [comment]
I've modified alignment.h to fix the issue.On 06 June 2017 at 21:34 John Lagerquist <notifications@github.com> wrote:working on a TI platform that does not support an 8-bit data type I get errors such as:"alignment.h", line 99: error: identifier "int8_t" is undefined typedef typename private_alignment::type_with_alignment_helper<ALIGNMENT, int8_t, int16_t, int32_t, int64_t, float, double, void*>::type type;this is the offending template:template <const size_t ALIGNMENT>
class type_with_alignment
{
public:

  typedef typename __private_alignment__::type_with_alignment_helper<ALIGNMENT, int8_t, int16_t, int32_t, int64_t, float, double, void*>::type type;
};

for now I have defined uint8_t=uint16_tthere should probably be a check based on your ETL_8BIT_SUPPORT macro—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
