### ISSUE TITLE
Arduino searchability

### ISSUE THREAD

**Issue by bmcdonnell** [ETLCPP/etl#321]
It took me a while to find the library in the Arduino Library Manager. It would help if the text "ETL" were included somewhere that the search field looks at. Apparently both the `name` and `sentence` fields in the `library.properties` file are options. (There may be others, IDK.)

Not found by searching "ETL":

![image](https://user-images.githubusercontent.com/35789100/102643793-c8047080-412d-11eb-8af3-ef001959a3f4.png)

Found by searching "embedded template":

![image](https://user-images.githubusercontent.com/35789100/102643845-e0748b00-412d-11eb-9343-57649995c8a6.png)

Searching by a word in the `sentence` field:

![image](https://user-images.githubusercontent.com/35789100/102643973-131e8380-412e-11eb-80e8-b60aab3bfba9.png)

**Comment by jwellbelove** [comment]
Would this work better?

name=Embedded Template Library (ETL)
version=19.3.5
author= John Wellbelove <john.wellbelove@etlcpp.com>
maintainer=John Wellbelove <john.wellbelove@etlcpp.com>
license=MIT
sentence=ETL. A C++ template library tailored for embedded systems.
paragraph=
category=Other
url=https://www.etlcpp.com/
architectures=*

**Comment by bmcdonnell** [comment]
Yup!

>

**Comment by jwellbelove** [comment]
Rather than modify the ETL repository directory layout or require scripts to be run on download or force users to use a ZIP library, I am creating an Arduino ETL repository which will be a fork of the latest ETL version, but with an Arduino compatible folder layout and minus the unit tests.

At the moment I am trying to figure out how I can update the Arduino's user contributed library entry for the ETL. They don't seem to make it very easy to find out.
