### ISSUE TITLE
etl::set : lower_bound does not behave as stl::set::lower_bound

### ISSUE THREAD

**Issue by NeimadG** [ETLCPP/etl#34]
In test_set, create a test that use (in pseudocode) : 
etl::set<int, 10> etlset;
and
stl::set<int> stlset;
both with values {0, 2, 4, 6, 8, 10, 12, 14, 16, 18}

with i in {1, 3, 5, 7, 9, 11, 13, 15, 17} : 
stlset.lower_bound(i) != etlset.lower_bound(i)

As result, etl::set::equal_range != stl::set::equal_range

Damien

**Comment by jwellbelove** [comment]
OK, I'll check that out and, if necessary, add to the unit tests.John.On 12 June 2017 at 11:02 NeimadG <notifications@github.com> wrote:In test_set, create a test that use (in pseudocode) : etl::set<int, 10> etlset; and stl::set stlset; both with values {0, 2, 4, 6, 8, 10, 12, 14, 16, 18}with i in {1, 3, 5, 7, 9, 11, 13, 15, 17} : stlset.lower_bound(i) != etlset.lower_bound(i)As result, etl::set::equal_range != stl::set::equal_rangeDamien—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by jwellbelove** [comment]
Do you know if this is still an issue?

**Comment by NeimadG** [comment]
Hi,
Yes the issue still exists. I've just cloned the repo and added a test fixture in test_set.cpp
Do you want me to push my new version ?

**Comment by jwellbelove** [comment]
You've fixed it, or written a test just to highlight it?

**Comment by NeimadG** [comment]
only written the test for now... I'm installing IDE for debugging, no fix yet

**Comment by jwellbelove** [comment]
If you could do a pull request for the test fixture to a 'hotfix' branch on Github, that would be great.

**Comment by NeimadG** [comment]
I have a fix, but I don't know how to use github... Am I allowed to create a branch for pull request ?

**Comment by jwellbelove** [comment]
Create a local hotfix branch on your computer and then do a pull request to the ETL project on github
Have you just done the test and fix for etl::set? I imagine the fix will be applicable to map, multimap & multiset too.

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by NeimadG** [comment]
I can have a look to the other containers. But I cannot push anything (or I don't know how to proceed). Don't I need to be a contributor ? Do I need some kind of privilege ?

**Comment by jwellbelove** [comment]
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

Or if you are really stuck, then send me a zip of your branch.

**Comment by NeimadG** [comment]
pull request open (from fork). I found issues on set & map only.

**Comment by jwellbelove** [comment]
Awesome! Thanks.
