### ISSUE TITLE
etl::array : unused variable

### ISSUE THREAD

**Issue by NeimadG** [ETLCPP/etl#35]
In etl::array, l.367 (void assign(TIterator first, TIterator last)),  itr is set but not used.

**Comment by jwellbelove** [comment]
Thanks, will fix today.John.On 12 June 2017 at 11:27 NeimadG <notifications@github.com> wrote:In etl::array, l.367 (void assign(TIterator first, TIterator last)), itr is set but not used.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by NeimadG** [comment]
Hi,
Isn't it fixed ?
