### ISSUE TITLE
etl::ilist::sort does not preserve equivalent nodes order

### ISSUE THREAD

**Issue by NeimadG** [ETLCPP/etl#37]
when sorting a list with some equal element, e.g. (list of ints, with operator<)
5, 15, 10 _(a)_, 10 _(b)_, 10 _(c)_, 20
the result is
5, 10 _(c)_, 10 _(b)_, 10 _(a)_, 15, 20
instead of
5, 10 _(a)_, 10 _(b)_, 10 _(c)_, 15, 20

where 10 _(a)_ denotes the int value 10 with address _a_

in ilist.h (on older version, I'm currently updating) replacing
else if (compare(*i_left, *i_right)
by
else if (!compare(*i_right, *i_left)

solves the problem

Cheers

**Comment by jwellbelove** [comment]
Thanks, I'll look into that. The sort is supposed to be stable.On 13 June 2017 at 10:58 NeimadG <notifications@github.com> wrote:when sorting a list with some equal element, e.g. (list of ints, with operator<) 5, 15, 10 (a), 10 (b), 10 (c), 20 the result is 5, 10 (c), 10 (b), 10 (a), 15, 20 instead of 5, 10 (a), 10 (b), 10 (c), 15, 20where 10 (a) denotes the int value 10 with address ain ilist.h (on older version, I'm currently updating) replacing else if (compare(*i_left, *i_right) by else if (!compare(*i_right, *i_left)solves the problemCheers—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by jwellbelove** [comment]
I shall also add to the unit tests to check that this will always be correct.

**Comment by jwellbelove** [comment]
Fixed in the latest release.
