### ISSUE TITLE
Add initializer-list constructor to `etl::set`

### ISSUE THREAD

**Issue by ArekSredzki** [ETLCPP/etl#67]
Currently initializing an `etl::set` instance with a few values rather long-form. Having access to an initializer-list constructor would be very useful.

**Comment by jwellbelove** [comment]
At the moment the ETL focuses on C++03 compatibility. There are already a few C++11 additions that can be enabled using a macro definition in the profile header and this may be another that could be added.
If I do add this functionality then I would like to make it applicable to all of the containers in the ETL. That's not to say it could not be done in stages rather than in one bit hit. I'll add it to the 'Jobs' list on Slack.

**Comment by jwellbelove** [comment]
I've made a start and modified about half a dozen containers so far.
It seems to be an easy update to do, so I should have all of them done by the end of the weekend.

**Comment by jwellbelove** [comment]
Just pushed the std::initializer_list constructor changes.

**Comment by ArekSredzki** [comment]
Awesome, thank you so much!
