### ISSUE TITLE
etl::span with own class

### ISSUE THREAD

**Issue by MickroC** [ETLCPP/etl#750]
I've just tried to update from 20.18.1 to 20.38.0.

Giving the following example code:
```
#include "span.h"
struct Data {
    size_t size() const {return 0;}
    int* data() const {return nullptr;}
};
Data data;
etl::span<int> test(data);
```
With 20.18.1, this code is valid. 

With 20.38.0, `etl::span` uses type traits and rejects `Data` instances (_no valid contructor found_).

I understand the intention of using type traits, so I am not sure about calling this a bug, but in my case it limits the usage of `etl::span`.
Is it possible to provide a less restrictive `etl::span` constructor or how do I have to change `Data` to be accepted?

**Comment by jwellbelove** [comment]
The way that `etl::span` worked before was not compliant with the API of `std::span` and caused issues where the incorrect constructor would be selected in certain circumstances. Additional checks to enable the correct constructor were added, which is why your code doesn't compile now.

To use the 'construct from container' constructor you must ensure that your struct/class contains a definition of `value_type`.

```
struct Data {
    using value_type = <the value type of Data>;
    size_t size() const {return 0;}
    int* data() const {return nullptr;}
};
Data data;
etl::span<int> test(data);
```
