### ISSUE TITLE
PlatformIO version seems out of date

### ISSUE THREAD

**Issue by skunktrading** [ETLCPP/etl#908]
Hi

I'm not sure if this is a PlatformIO issue or whether something need to be done on your side, but the version available in the PlatformIO registry has been stuck at 20.38.11 for a few months now. Should I raise this with PlatformIO support?

**Comment by jwellbelove** [comment]
POI Updated

**Comment by labodj** [comment]
@jwellbelove instead of opening a new issue for this very same reason I'll just leave this comment here, the library seems outdated in PIO registry (the last one is 20.39.4), could you please update the package there? In addition to that I think it can be useful to setup a CI flow to upload to PIO Library on every release.

**Comment by jwellbelove** [comment]
I'll look at adding it to Github Actions on the next release.
